from sqlmodel import Session
from database import engine, create_db_and_tables  
from database import Company, Product, Policy
import json

def seed_database():
    create_db_and_tables()
    with Session(engine) as session:
        # --- 1. GLOBAL TRUST BANK (Traditional Banking) ---
        bank = Company(name="Global Trust Bank", domain="Banking")
        session.add(bank)
        session.commit()
        session.refresh(bank)

        session.add_all([
            Product(company_id=bank.id, product_name="Elite Savings", description="High-interest savings account."),
            Product(company_id=bank.id, product_name="Travel Rewards Card", description="Credit card with zero forex fees.")
        ])

        session.add_all([
            Policy(company_id=bank.id, policy_type="Identity Verification", rules_json=json.dumps([
                "Agent must ask for full name",
                "Agent must verify last 4 digits of ID or SSN",
                "Agent must confirm the customer's date of birth"
            ])),
            Policy(company_id=bank.id, policy_type="Fraud Alert", rules_json=json.dumps([
                "If customer says 'stolen' or 'fraud', agent must immediately freeze the account",
                "Agent must warn: 'We never ask for your full PIN over the phone'"
            ]))
        ])

        # --- 2. NEXUS DIGITAL BANK (Modern Fintech) ---
        fintech = Company(name="Nexus Digital Bank", domain="Banking")
        session.add(fintech)
        session.commit()
        session.refresh(fintech)

        session.add_all([
            Product(company_id=fintech.id, product_name="Crypto-Yield Wallet", description="Stablecoin interest-bearing account."),
            Product(company_id=fintech.id, product_name="AI-Portfolios", description="Robo-advisory investment tool.")
        ])

        session.add_all([
            Policy(company_id=fintech.id, policy_type="AI Transparency", rules_json=json.dumps([
                "Agent must disclose if a recommendation was generated by an AI model",
                "Mandatory disclaimer: 'AI insights are for information only, not legal financial advice'"
            ])),
            Policy(company_id=fintech.id, policy_type="Digital Asset Security", rules_json=json.dumps([
                "Never ask for the customer's 12-word seed phrase or private key",
                "Verify 2FA status before discussing wallet transfers"
            ]))
        ])

        # --- 3. SKYLINK MOBILE (Standard Telecom) ---
        telco = Company(name="SkyLink Mobile", domain="Telecom")
        session.add(telco)
        session.commit()
        session.refresh(telco)

        session.add_all([
            Product(company_id=telco.id, product_name="Unlimited 5G Plan", description="Unlimited data with no throttling."),
            Product(company_id=telco.id, product_name="Fiber-to-Home", description="High-speed home broadband.")
        ])

        session.add_all([
            Policy(company_id=telco.id, policy_type="Service Outage", rules_json=json.dumps([
                "Agent must perform a network outage check for the user's area",
                "If outage is found, agent must provide an Estimated Time of Restoration (ETR)",
                "Agent must offer a data voucher if outage exceeds 4 hours"
            ]))
        ])

        # --- 4. APEX CONNECT (Premium Telecom) ---
        premium_telco = Company(name="Apex Connect", domain="Telecom")
        session.add(premium_telco)
        session.commit()
        session.refresh(premium_telco)

        session.add_all([
            Product(company_id=premium_telco.id, product_name="Global Roaming Pro", description="Zero-cost roaming in 150 countries."),
            Product(company_id=premium_telco.id, product_name="Family Vault 1TB", description="Shared family cloud storage.")
        ])

        session.add_all([
            Policy(company_id=premium_telco.id, policy_type="Billing Dispute", rules_json=json.dumps([
                "Agent must explain 'Bill Shock' protection if charges exceed $100",
                "For duplicate charges, agent must issue a credit immediately",
                "Agent must verify usage dates in the Call Detail Record (CDR)"
            ])),
            Policy(company_id=premium_telco.id, policy_type="Customer Retention", rules_json=json.dumps([
                "If customer says 'cancel', agent must offer the 'Loyalty Discount'",
                "Agent must mention the 'Contract Buyout' program if customer is switching providers"
            ]))
        ])

        session.commit()
        print("Successfully seeded 4 companies with unique policies!")

if __name__ == "__main__":
    seed_database()